image: "mcr.microsoft.com/mssql/server:2022"
imageTag: "2022-latest"
imagePullPolicy: IfNotPresent
acceptEULA: "Y"
mssql-password: "Yukon900"

## Persist data to a persitent volume
persistence:
  enabled: true
  existingClaim: mssql-server-linux-claim

  ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
  ## Default: volume.alpha.kubernetes.io/storage-class: default
  ##
  # storageClass:
  accessMode: ReadWriteOnce
  size: 8Gi
  subPath: "mssql-db"
resources:
  requests:
    memory: 4Gi
    cpu: 1